import { useState } from "react";
import { Button } from "@/components/ui/button";
import { FileText, Copy, RefreshCw, Check } from "lucide-react";
import { toast } from "sonner";

interface DescriptionPanelProps {
  isOpen: boolean;
}

const sampleDescriptions = [
  {
    title: "Professional Product Description",
    content: "Elevate your e-commerce presence with this premium product. Expertly crafted with attention to detail, featuring ergonomic design and modern aesthetics. Perfect for discerning customers who value quality and style. Industry-leading durability meets contemporary design."
  },
  {
    title: "Quick Social Media Caption",
    content: "✨ Transform your space with style! Premium quality meets modern design. Shop now and experience the difference. #ProductExcellence #EcommercePro"
  }
];

export const DescriptionPanel = ({ isOpen }: DescriptionPanelProps) => {
  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("Copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleGenerate = () => {
    setIsGenerating(true);
    toast.loading("Generating descriptions...");
    setTimeout(() => {
      setIsGenerating(false);
      toast.success("Descriptions generated!");
    }, 1500);
  };

  if (!isOpen) return null;

  return (
    <div className="bg-card rounded-2xl p-8 shadow-soft border border-border animate-scale-in">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-secondary/10 flex items-center justify-center">
            <FileText className="w-5 h-5 text-secondary" />
          </div>
          <div>
            <h2 className="text-xl font-bold">AI Descriptions</h2>
            <p className="text-sm text-muted-foreground">Marketing copy generated by AI</p>
          </div>
        </div>
        <Button 
          onClick={handleGenerate}
          disabled={isGenerating}
          variant="outline"
          className="border-secondary text-secondary hover:bg-secondary/10"
        >
          <RefreshCw className={`w-4 h-4 mr-2 ${isGenerating ? 'animate-spin' : ''}`} />
          Regenerate
        </Button>
      </div>

      <div className="space-y-4">
        {sampleDescriptions.map((desc, idx) => (
          <div 
            key={idx}
            className="p-6 bg-gradient-to-br from-muted to-muted/50 rounded-xl border border-border hover:shadow-soft transition-all duration-300"
          >
            <div className="flex items-start justify-between gap-4 mb-3">
              <h3 className="font-semibold text-sm text-muted-foreground">{desc.title}</h3>
              <Button
                size="icon"
                variant="ghost"
                onClick={() => handleCopy(desc.content)}
                className="shrink-0"
              >
                {copied ? (
                  <Check className="w-4 h-4 text-primary" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
              </Button>
            </div>
            <p className="text-sm leading-relaxed">{desc.content}</p>
          </div>
        ))}
      </div>

      <div className="mt-6 p-4 bg-primary/5 rounded-xl border border-primary/20">
        <div className="flex items-start gap-3">
          <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
            <FileText className="w-4 h-4 text-primary" />
          </div>
          <div className="text-sm">
            <p className="font-medium mb-1">AI-Powered Insights</p>
            <p className="text-muted-foreground text-xs">
              These descriptions highlight industry relevance, ergonomic design, usability, and style - optimized for maximum engagement.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
